/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.paz1c.gui.PrihlasenieRegistracia;

import com.paz1c.constants.Nastavenia;
import java.awt.Container;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sakacova
 */
public class VyberModu extends javax.swing.JPanel {

    private RegistraciaPrihlasenie parentJFrame;
    
    public VyberModu() {
        initComponents();
    }
    
    public void setParent(RegistraciaPrihlasenie parent){
        parentJFrame = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        zamestnanecToggle = new javax.swing.JToggleButton();
        cviciaciToggle = new javax.swing.JToggleButton();
        prihlasenieButton = new javax.swing.JButton();
        registraciaButton = new javax.swing.JButton();
        uvitaciTextLabel = new javax.swing.JLabel();
        popisTextLabel = new javax.swing.JLabel();
        zmenaJazykaPanel = new com.paz1c.gui.PrihlasenieRegistracia.zmenaJazykaPanel();

        setBackground(new java.awt.Color(255, 250, 226));
        setForeground(new java.awt.Color(153, 153, 255));
        setMaximumSize(new java.awt.Dimension(2000, 2000));
        setMinimumSize(new java.awt.Dimension(0, 0));

        buttonGroup.add(zamestnanecToggle);
        zamestnanecToggle.setText("Zamestnanie");
        zamestnanecToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamestnanecToggleActionPerformed(evt);
            }
        });

        buttonGroup.add(cviciaciToggle);
        cviciaciToggle.setText("Športové zariadenie");
        cviciaciToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cviciaciToggleActionPerformed(evt);
            }
        });

        prihlasenieButton.setText("Prihlásiť sa");
        prihlasenieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prihlasenieButtonActionPerformed(evt);
            }
        });

        registraciaButton.setText("Registrácia");
        registraciaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registraciaButtonActionPerformed(evt);
            }
        });

        uvitaciTextLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uvitaciTextLabel.setText("Vítame Vás!");

        popisTextLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        popisTextLabel.setText("Vyberte si mód a zaregistrujte sa alebo sa prihláste ak už máte účet.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(prihlasenieButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registraciaButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(zamestnanecToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cviciaciToggle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(popisTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 40, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(uvitaciTextLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(zmenaJazykaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uvitaciTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zmenaJazykaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(popisTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(135, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zamestnanecToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cviciaciToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registraciaButton)
                    .addComponent(prihlasenieButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void prihlasenieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prihlasenieButtonActionPerformed
       parentJFrame.otvorOkno("prihlasenie");
    }//GEN-LAST:event_prihlasenieButtonActionPerformed

    private void registraciaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraciaButtonActionPerformed
        if(Nastavenia.vybranyMod != null){
            parentJFrame.otvorOkno("registracia");
        }else{
            JOptionPane.showMessageDialog(parentJFrame,"Neni vybraty ziaden mod","Vyber modu",JOptionPane.ERROR_MESSAGE);
        }
        System.out.println(Nastavenia.vybranyMod);
    }//GEN-LAST:event_registraciaButtonActionPerformed

    private void zamestnanecToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamestnanecToggleActionPerformed
        if(zamestnanecToggle.isSelected())
            Nastavenia.vybranyMod = "Zamestnanec";
    }//GEN-LAST:event_zamestnanecToggleActionPerformed

    private void cviciaciToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cviciaciToggleActionPerformed
        if(cviciaciToggle.isSelected())
            Nastavenia.vybranyMod = "Cviciaci";
    }//GEN-LAST:event_cviciaciToggleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JToggleButton cviciaciToggle;
    private javax.swing.JLabel popisTextLabel;
    private javax.swing.JButton prihlasenieButton;
    private javax.swing.JButton registraciaButton;
    private javax.swing.JLabel uvitaciTextLabel;
    private javax.swing.JToggleButton zamestnanecToggle;
    private com.paz1c.gui.PrihlasenieRegistracia.zmenaJazykaPanel zmenaJazykaPanel;
    // End of variables declaration//GEN-END:variables
}
